import type { CardContent } from './types';

// Session 15 · Data Science (Module Session 2) · 19.08.2026
// Dr. Zuari's SQL/SQLite session: DBMS concept, primary/foreign keys, sqlite3 in Python, building a DB with an agent.
// Cards authored from transcript analysis. Original teaching material.

export const session15Cards: CardContent[] = [
  {
    number: '00',
    title: { en: `Session Index`, he: `מפתח המפגש` },
    subtitle: {
      en: `An eleven-card map — the language sitting behind every app that has ever stored a single row of data`,
      he: `מפתח של אחד-עשר כרטיסים — השפה שיושבת מאחורי כל אפליקציה שאי-פעם שמרה שורת נתונים אחת`,
    },
    sections: [
      {
        heading: { en: `What This Session Is`, he: `מה המפגש הזה` },
        body: {
          en: `Databases finally enter the picture — the missing piece behind every app that remembers a customer, a product, or an order. The session covers what a DBMS actually is, SQL vocabulary, the primary-key/foreign-key relationship that lets tables connect, the full sqlite3-in-Python workflow, and closes by building a small reservation-system database with an agent.`,
          he: `בסיסי נתונים סוף סוף נכנסים לתמונה — החלק החסר שמאחורי כל אפליקציה שזוכרת לקוח, מוצר, או הזמנה. המפגש מכסה מה DBMS באמת, אוצר מילים של SQL, יחס מפתח-ראשי/מפתח-זר שמאפשר לטבלאות להתחבר, את כל זרימת העבודה של sqlite3 בפייתון, ונסגר בבניית בסיס נתונים קטן למערכת הזמנות עם סוכן.`,
        },
      },
      {
        heading: { en: `How to Use`, he: `איך להשתמש` },
        body: {
          en: `Card 01 is the pedagogical trick Dr. Zuari used to open the session — worth understanding before anything else. Card 04 covers the exact moment "everyone fell for it" tracing a chain of foreign keys — read it slowly.`,
          he: `כרטיס 01 הוא התרגיל הפדגוגי שד״ר זוארי השתמש בו כדי לפתוח את המפגש — כדאי להבין אותו לפני כל דבר אחר. כרטיס 04 מכסה את הרגע המדויק שבו "כולם נפלו בזה" בעקיבה אחרי שרשרת מפתחות זרים — כדאי לקרוא לאט.`,
        },
      },
    ],
    principle: {
      en: `Every application with a memory has a database sitting behind it — this session is where that invisible layer finally gets a name and a grammar.`,
      he: `לכל אפליקציה עם זיכרון יש בסיס נתונים יושב מאחוריה — המפגש הזה הוא איפה שהשכבה הבלתי-נראית הזו סוף סוף מקבלת שם ודקדוק.`,
    },
  },
  {
    number: '01',
    title: { en: `Panic Removal`, he: `הסרת פאניקה` },
    subtitle: {
      en: `Showing unfamiliar SQL cold, before a single rule of syntax is taught, on purpose`,
      he: `הצגת SQL לא מוכר בקור, לפני שנלמד כלל תחביר אחד, בכוונה`,
    },
    sections: [
      {
        heading: { en: `A Slide Titled Exactly That`, he: `שקף שנקרא בדיוק ככה` },
        body: {
          en: `Dr. Zuari opened with a slide he literally labeled "panic removal": a full SQL query, projected with zero explanation, and a direct question — what do you think this does? Students guessed correctly from the English words alone — \`SELECT\`, \`FROM\`, \`WHERE\` — before a single formal rule had been taught.`,
          he: `ד״ר זוארי פתח עם שקף שהוא כינה פשוטו כמשמעו "הסרת פאניקה": שאילתת SQL מלאה, מוקרנת בלי הסבר בכלל, ושאלה ישירה — מה אתם חושבים שהדבר הזה עושה? סטודנטים ניחשו נכון רק מהמילים באנגלית — \`SELECT\`, \`FROM\`, \`WHERE\` — לפני שכלל פורמלי אחד נלמד.`,
        },
      },
      {
        heading: { en: `Why Desensitize First, Explain Second`, he: `למה לחסן קודם, להסביר אחר כך` },
        body: {
          en: `The stated goal wasn't fluency in writing SQL from scratch — it was recognition. Dr. Zuari was explicit that most SQL in a student's future will be generated by an agent, and the win is being able to glance at it and know what it's asking for, rather than seeing unfamiliar syntax and blindly trusting the tool that wrote it.`,
          he: `המטרה המוצהרת לא הייתה שטף בכתיבת SQL מאפס — היא הייתה זיהוי. ד״ר זוארי היה מפורש שרוב ה-SQL בעתידה של סטודנטית ייוצר על ידי סוכן, וההצלחה היא היכולת להעיף מבט ולדעת מה זה מבקש, במקום לראות תחביר לא מוכר ולסמוך בעיוורון על הכלי שכתב אותו.`,
        },
      },
    ],
    principle: {
      en: `The goal of this session was never to write SQL fluently from memory — it was to never feel panic when an agent hands you a query and you have to check its work.`,
      he: `המטרה של המפגש הזה לעולם לא הייתה לכתוב SQL בשטף מהזיכרון — היא הייתה לעולם לא להרגיש פאניקה כשסוכן מוסר לך שאילתה ואת צריכה לבדוק את העבודה שלו.`,
    },
  },
  {
    number: '02',
    title: { en: `SQLite Needs No Installation — But You Do Need a Viewer`, he: `SQLite לא צריכה התקנה — אבל את כן צריכה כלי צפייה` },
    subtitle: {
      en: `The database file itself shows absolutely nothing — an editor extension is the only way to actually see inside it`,
      he: `קובץ בסיס הנתונים עצמו לא מראה שום דבר — תוסף עורך הוא הדרך היחידה באמת לראות מה בפנים`,
    },
    sections: [
      {
        heading: { en: `Why SQLite for This Session`, he: `למה SQLite למפגש הזה` },
        body: {
          en: `Dr. Zuari picked SQLite specifically because it ships built into Python already — no server, no cloud setup, no extra \`pip install\`. That's a deliberate trade-off: SQLite isn't what a real production app should run on, but it's the fastest path to understanding what a database actually does before adding cloud complexity next session with Supabase.`,
          he: `ד״ר זוארי בחר ב-SQLite ספציפית כי היא מגיעה מובנית בתוך פייתון כבר — בלי שרת, בלי הקמת ענן, בלי \`pip install\` נוסף. זה טרייד-אוף מכוון: SQLite היא לא מה שאפליקציית פרודקשן אמיתית צריכה לרוץ עליה, אבל היא הנתיב הכי מהיר להבנת מה בסיס נתונים בעצם עושה לפני שמוסיפים מורכבות ענן במפגש הבא עם Supabase.`,
        },
      },
      {
        heading: { en: `The File That Refuses to Show Anything`, he: `הקובץ שמסרב להראות כל דבר` },
        body: {
          en: `Creating a database produces a \`.db\` file that, opened directly, displays nothing at all — no table, no error, just silence. This confused several students until they installed the SQLite Viewer extension, which is what actually renders the tables and rows visually. Without it, the only proof a database has anything in it is running a query and reading the returned result.`,
          he: `יצירת בסיס נתונים מייצרת קובץ \`.db\` שכשפותחים אותו ישירות, לא מציג כלום — בלי טבלה, בלי שגיאה, רק שקט. זה בלבל כמה סטודנטים עד שהתקינו את תוסף SQLite Viewer, שהוא מה שבאמת מרנדר את הטבלאות והשורות ויזואלית. בלעדיו, ההוכחה היחידה שיש משהו בבסיס נתונים היא להריץ שאילתה ולקרוא את התוצאה שחוזרת.`,
        },
      },
    ],
    principle: {
      en: `A database file being silent is not the same as a database file being empty — you need the right tool before you can tell the difference.`,
      he: `קובץ בסיס נתונים שקט הוא לא אותו דבר כמו קובץ בסיס נתונים ריק — צריך את הכלי הנכון לפני שאפשר להבדיל בין השניים.`,
    },
  },
  {
    number: '03',
    title: { en: `Connect, Cursor, Execute, Commit, Close`, he: `Connect, Cursor, Execute, Commit, Close` },
    subtitle: {
      en: `The five-step sqlite3-in-Python sequence, and why forgetting commit means the change never actually happened`,
      he: `רצף חמשת השלבים של sqlite3 בפייתון, ולמה לשכוח commit אומר שהשינוי לעולם לא באמת קרה`,
    },
    sections: [
      {
        heading: { en: `Connect Creates or Reconnects`, he: `Connect יוצר או מתחבר מחדש` },
        body: {
          en: `\`sqlite3.connect('file.db')\` does one of two things depending on whether the file already exists: it creates a brand-new, empty database, or it reconnects to the one already sitting there. A \`cursor\`, pulled from that connection, is the object that actually carries SQL commands back and forth — nothing runs without it.`,
          he: `\`sqlite3.connect('file.db')\` עושה אחד משני דברים בהתאם לשאלה אם הקובץ כבר קיים: הוא יוצר בסיס נתונים חדש לגמרי וריק, או מתחבר מחדש לזה שכבר יושב שם. \`cursor\`, שנשלף מהחיבור הזה, הוא האובייקט שבפועל נושא פקודות SQL הלוך ושוב — שום דבר לא רץ בלעדיו.`,
        },
      },
      {
        heading: { en: `Commit Is Not Optional`, he: `Commit הוא לא אופציונלי` },
        body: {
          en: `Running \`cursor.execute('CREATE TABLE ...')\` builds the table only in a temporary, in-progress state — \`conn.commit()\` is the separate step that actually saves it to the database file. Dr. Zuari's demonstration was direct: skip commit, and the change vanishes the moment the connection closes, as if it never happened.`,
          he: `הרצת \`cursor.execute('CREATE TABLE ...')\` בונה את הטבלה רק במצב זמני, באמצע תהליך — \`conn.commit()\` הוא השלב הנפרד שבאמת שומר אותה לקובץ בסיס הנתונים. ההדגמה של ד״ר זוארי הייתה ישירה: לדלג על commit, והשינוי נעלם ברגע שהחיבור נסגר, כאילו זה מעולם לא קרה.`,
        },
      },
      {
        heading: { en: `with Handles the Closing for You`, he: `with מטפלת בסגירה בשבילך` },
        body: {
          en: `Forgetting to close a connection is easy to do and easy to forget noticing. Wrapping the whole block in \`with sqlite3.connect('file.db') as conn:\` guarantees the connection closes automatically the moment the block ends — the same open-write-close discipline as working with a plain text file, just applied to a database.`,
          he: `לשכוח לסגור חיבור זה קל לעשות וקל לשכוח לשים לב אליו. עטיפת כל הבלוק ב-\`with sqlite3.connect('file.db') as conn:\` מבטיחה שהחיבור נסגר אוטומטית ברגע שהבלוק מסתיים — אותה משמעת של פתח-כתוב-סגור כמו עבודה עם קובץ טקסט רגיל, פשוט מיושמת על בסיס נתונים.`,
        },
      },
    ],
    principle: {
      en: `Executing a command changes nothing permanent by itself — commit is the step that turns a temporary action into a saved fact.`,
      he: `הרצת פקודה לא משנה שום דבר קבוע בעצמה — commit הוא השלב שהופך פעולה זמנית לעובדה שמורה.`,
    },
  },
  {
    number: '04',
    title: { en: `A Foreign Key Points to a Row, Not a Number`, he: `מפתח זר מצביע על שורה, לא על מספר` },
    subtitle: {
      en: `Tracing 2 → address_id 2 → city_id 2 is not the same as reading "2" three times — the class fell for exactly this`,
      he: `לעקוב אחרי 2 ← address_id 2 ← city_id 2 זה לא אותו דבר כמו לקרוא "2" שלוש פעמים — הכיתה נפלה בדיוק בזה`,
    },
    sections: [
      {
        heading: { en: `The Exercise That Caught Everyone`, he: `התרגיל שתפס את כולם` },
        body: {
          en: `With a chain of three linked tables — Cities, Addresses, Users — Dr. Zuari asked what city a specific user lived in. Nearly the entire class answered instantly and confidently wrong, because they matched the digit itself rather than tracing what that digit was actually a reference to at each hop of the chain.`,
          he: `עם שרשרת של שלוש טבלאות מקושרות — ערים, כתובות, משתמשים — ד״ר זוארי שאל באיזו עיר משתמשת מסוימת גרה. כמעט כל הכיתה ענתה מיד ובביטחון לא נכון, כי הם התאימו את הספרה עצמה במקום לעקוב אחרי מה שהספרה הזו בעצם הייתה הפניה אליו בכל קפיצה בשרשרת.`,
        },
      },
      {
        heading: { en: `Why the Mistake Happens`, he: `למה הטעות קורית` },
        body: {
          en: `A user row holding \`address_id = 2\` does not mean city number 2 — it means the address whose own \`id\` is 2, and only that address row's own \`city_id\` value says which city applies. Every foreign key is a pointer to a specific row in another table, not a shortcut straight to the final answer, and skipping a hop in the chain is exactly how the whole class got it wrong together.`,
          he: `שורת משתמשת שמחזיקה \`address_id = 2\` לא אומרת עיר מספר 2 — היא אומרת את הכתובת שה-\`id\` שלה עצמה הוא 2, ורק ערך ה-\`city_id\` של שורת הכתובת הזו עצמה אומר איזו עיר חלה. כל מפתח זר הוא מצביע לשורה ספציפית בטבלה אחרת, לא קיצור ישר לתשובה הסופית, ולדלג על קפיצה בשרשרת זה בדיוק איך כל הכיתה טעתה ביחד.`,
        },
      },
    ],
    principle: {
      en: `Following a foreign key means following it one hop at a time — collapsing the chain and matching digits by eye is exactly how confident wrong answers happen.`,
      he: `לעקוב אחרי מפתח זר אומר לעקוב אחריו קפיצה אחת בכל פעם — לקפל את השרשרת ולהתאים ספרות במבט זה בדיוק איך תשובות שגויות ובטוחות קורות.`,
    },
  },
  {
    number: '05',
    title: { en: `One Big Table or Several Small Ones`, he: `טבלה גדולה אחת או כמה קטנות` },
    subtitle: {
      en: `A thought experiment about fixing a typo decides the answer — count how many rows you'd have to touch`,
      he: `ניסוי מחשבתי על תיקון שגיאת הקלדה מחליט את התשובה — סופרים כמה שורות היית צריכה לגעת בהן`,
    },
    sections: [
      {
        heading: { en: `The Pushback Was Reasonable`, he: `ההתנגדות הייתה הגיונית` },
        body: {
          en: `A student asked directly: what's the point of splitting data across tables at all — wouldn't one giant table with everything be simpler? Dr. Zuari didn't dismiss the question; splitting tables genuinely does add complexity, and the justification has to earn its keep.`,
          he: `סטודנטית שאלה ישירות: מה הטעם בכלל לפצל נתונים בין טבלאות — האם טבלה ענקית אחת עם הכול לא הייתה פשוטה יותר? ד״ר זוארי לא פטר את השאלה; פיצול טבלאות באמת מוסיף מורכבות, וההצדקה צריכה להצדיק את עצמה.`,
        },
      },
      {
        heading: { en: `Count the Fixes, Not the Tables`, he: `סופרים את התיקונים, לא את הטבלאות` },
        body: {
          en: `The demonstration: a city name misspelled and repeated across many customer rows in one giant table requires a separate fix for every single row it appears in. Move that city into its own small table, referenced everywhere else by a foreign key, and the same typo needs exactly one fix — in one row, one time — no matter how many customers point to it.`,
          he: `ההדגמה: שם עיר שגוי בהקלדה וחוזר על עצמו בהרבה שורות לקוחות בטבלה ענקית אחת דורש תיקון נפרד לכל שורה בודדת שהוא מופיע בה. להעביר את העיר הזו לטבלה קטנה משלה, שמופנית אליה בכל מקום אחר עם מפתח זר, והתקלדה הזהה דורשת בדיוק תיקון אחד — בשורה אחת, פעם אחת — לא משנה כמה לקוחות מצביעים עליה.`,
        },
      },
    ],
    principle: {
      en: `Splitting into multiple tables isn't complexity for its own sake — it's the design that turns a hundred required fixes into one.`,
      he: `פיצול לכמה טבלאות הוא לא מורכבות לשם עצמה — זה העיצוב שהופך מאה תיקונים נדרשים לתיקון אחד.`,
    },
  },
  {
    number: '06',
    title: { en: `Running INSERT Twice Doesn't Error — It Duplicates`, he: `להריץ INSERT פעמיים לא מפילה שגיאה — היא משכפלת` },
    subtitle: {
      en: `SQLite has no memory of what already ran — every execution of an insert cell is a brand-new set of rows`,
      he: `ל-SQLite אין זיכרון של מה שכבר רץ — כל הרצה של תא הכנסה היא סט חדש לגמרי של שורות`,
    },
    sections: [
      {
        heading: { en: `Where the Confusion Came From`, he: `מאיפה הבלבול הגיע` },
        body: {
          en: `A student re-ran a notebook cell that inserted two book records several times while testing, and ended up with eight duplicate rows instead of two. Nothing errored, because SQLite has no concept of "this insert already happened" — each execution is independent, and the auto-incrementing primary key happily hands out a fresh ID to every duplicate.`,
          he: `סטודנטית הריצה מחדש תא במחברת שהכניס שני רשומות ספרים כמה פעמים בזמן בדיקה, ונשארה עם שמונה שורות כפולות במקום שתיים. שום דבר לא הפיל שגיאה, כי ל-SQLite אין מושג של "ההכנסה הזו כבר קרתה" — כל הרצה עצמאית, והמפתח הראשי שמעלה את עצמו אוטומטית מוסר בשמחה מזהה טרי לכל כפילות.`,
        },
      },
      {
        heading: { en: `A Guard Flag, and Its Honest Limit`, he: `דגל שמירה, והגבול הכן שלו` },
        body: {
          en: `A rough fix explored live: a boolean flag, set only after the insert successfully runs, checked before running it again. Dr. Zuari was honest that this doesn't fully solve the problem — restarting the script resets the flag right along with everything else. His closing point mattered more than the fix: in a real application, you are almost never the one manually inserting data — customers generate it through the app itself, so this exact failure mode rarely shows up outside of a learning notebook.`,
          he: `תיקון גס שנחקר בשידור חי: דגל בוליאני, שנקבע רק אחרי שההכנסה רצה בהצלחה, נבדק לפני שמריצים אותה שוב. ד״ר זוארי היה כן שזה לא פותר את הבעיה לגמרי — הפעלה מחדש של הסקריפט מאפסת את הדגל בדיוק כמו כל דבר אחר. הנקודה הסוגרת שלו הייתה חשובה יותר מהתיקון: באפליקציה אמיתית, את כמעט אף פעם לא זו שמכניסה נתונים ידנית — לקוחות מייצרים אותם דרך האפליקציה עצמה, אז כשל הדפוס המדויק הזה לעיתים נדירות מופיע מחוץ למחברת לימוד.`,
        },
      },
    ],
    principle: {
      en: `A database has no memory of your intentions, only of what actually ran — re-running an insert isn't a repeat, it's a brand-new event.`,
      he: `לבסיס נתונים אין זיכרון של הכוונות שלך, רק של מה שבאמת רץ — הרצה חוזרת של הכנסה היא לא חזרה, היא אירוע חדש לגמרי.`,
    },
  },
  {
    number: '07',
    title: { en: `Build a Small Database With an Agent`, he: `בונות בסיס נתונים קטן עם סוכן` },
    subtitle: {
      en: `A terminal trick, a plain-language schema request, and the discipline of reading the generated CREATE TABLE code`,
      he: `טריק טרמינל, בקשת סכימה בשפה פשוטה, והמשמעת של קריאת קוד ה-CREATE TABLE שנוצר`,
    },
    sections: [
      {
        heading: { en: `Steps`, he: `שלבים` },
        body: {
          en: `One: open a fresh folder for the project, then open a terminal inside it and type \`code .\` rather than manually navigating through the editor's open-project menu — a small shortcut Dr. Zuari called out as worth learning early. Two: describe the system in plain language — a simple SQLite-based reservation system that lets a travel agent check which flights have open seats. Three: let the agent generate the schema and the insert logic. Four: before trusting any of it, open the generated code and read how each table and column is actually defined.`,
          he: `אחת: לפתוח תיקייה טרייה לפרויקט, ואז לפתוח טרמינל בתוכה ולהקליד \`code .\` במקום לנווט ידנית דרך תפריט פתיחת-פרויקט של העורך — קיצור קטן שד״ר זוארי ציין ככדאי ללמוד מוקדם. שתיים: לתאר את המערכת בשפה פשוטה — מערכת הזמנות פשוטה מבוססת SQLite שנותנת לסוכן נסיעות לבדוק אילו טיסות יש בהן מקום פנוי. שלוש: לתת לסוכן לייצר את הסכימה ואת לוגיקת ההכנסה. ארבע: לפני שסומכים על משהו מזה, לפתוח את הקוד שנוצר ולקרוא איך כל טבלה ועמודה בעצם מוגדרת.`,
        },
      },
      {
        heading: { en: `What the Agent Produced`, he: `מה הסוכן ייצר` },
        body: {
          en: `The result: eight interconnected tables — flights, airports, seats, customer bookings, and more — created with a single plain-language request, complete with the connecting foreign keys already wired up. Dr. Zuari's insistence throughout: this is exactly the "code that keeps showing up" from Claude that the whole session was preparing students to actually read.`,
          he: `התוצאה: שמונה טבלאות מקושרות — טיסות, שדות תעופה, מושבים, הזמנות לקוחות, ועוד — נוצרו בבקשה אחת בשפה פשוטה, כולל המפתחות הזרים המחברים שכבר חוטו. ההתעקשות של ד״ר זוארי לאורך כל הדרך: זה בדיוק "הקוד שממשיך לצוץ" מ-Claude שכל המפגש הכין את הסטודנטים לבאמת לקרוא.`,
        },
      },
    ],
    principle: {
      en: `An agent can build the whole schema in one request — the discipline the session built was making sure you can still read exactly what it built.`,
      he: `סוכן יכול לבנות את כל הסכימה בבקשה אחת — המשמעת שהמפגש בנה הייתה לוודא שאת עדיין יכולה לקרוא בדיוק מה שהוא בנה.`,
    },
  },
  {
    number: '08',
    title: { en: `Check the Column Definitions, Not Just the Table Names`, he: `בדקי את הגדרות העמודות, לא רק את שמות הטבלאות` },
    subtitle: {
      en: `An agent-generated schema is only as trustworthy as the type and key decisions hiding inside each column`,
      he: `סכימה שנוצרה בידי סוכן אמינה רק כמו החלטות הטיפוס והמפתח שמתחבאות בתוך כל עמודה`,
    },
    sections: [
      {
        heading: { en: `Where to Actually Look`, he: `איפה באמת להסתכל` },
        body: {
          en: `Watching over students' shoulders as they built with an agent, Dr. Zuari repeated one instruction more than any other: don't just glance at the table names — look at how each column is defined. Is \`id\` marked as a primary key? Is it set to auto-increment? Does a foreign key correctly reference the right table and column?`,
          he: `כשד״ר זוארי צפה מעל הכתפיים של הסטודנטים בזמן שבנו עם סוכן, הוא חזר על הוראה אחת יותר מכל אחרת: אל תסתכלי רק על שמות הטבלאות — הסתכלי איך כל עמודה מוגדרת. האם \`id\` מסומנת כמפתח ראשי? האם היא מוגדרת להעלות את עצמה אוטומטית? האם מפתח זר מפנה נכון לטבלה ולעמודה הנכונות?`,
        },
      },
      {
        heading: { en: `Why This Habit Outlasts the Session`, he: `למה ההרגל הזה שורד מעבר למפגש` },
        body: {
          en: `Table creation itself is now nearly instant — one sentence to an agent produces a working schema in seconds. What hasn't gotten any faster is the cost of a wrong column type or a missing foreign key surfacing weeks later, buried inside a bug that has nothing obviously to do with the schema. Reading the CREATE TABLE statement once, right after it's generated, is far cheaper than debugging its consequences later.`,
          he: `יצירת טבלה עצמה היא כבר כמעט מיידית — משפט אחד לסוכן מייצר סכימה עובדת תוך שניות. מה שלא נהיה מהיר יותר זה העלות של טיפוס עמודה שגוי או מפתח זר חסר שצץ שבועות אחר כך, קבור בתוך באג שאין לו קשר גלוי לסכימה. לקרוא את הצהרת ה-CREATE TABLE פעם אחת, מיד אחרי שהיא נוצרת, זול הרבה יותר מלנפות את ההשלכות שלה אחר כך.`,
        },
      },
    ],
    principle: {
      en: `Speed of generation and correctness of structure are two different claims — an agent guarantees the first, never the second.`,
      he: `מהירות יצירה ונכונות מבנה הן שתי טענות שונות — סוכן מבטיח את הראשונה, לעולם לא את השנייה.`,
    },
  },
  {
    number: '09',
    title: { en: `Why You Can't Reorder SELECT, FROM, WHERE`, he: `למה אי אפשר לסדר מחדש SELECT, FROM, WHERE` },
    subtitle: {
      en: `The way a query is written and the order it's actually evaluated in are two different things, on purpose`,
      he: `האופן שבו שאילתה נכתבת והסדר שהיא באמת מוערכת בו הם שני דברים שונים, בכוונה`,
    },
    sections: [
      {
        heading: { en: `The Question That Exposed It`, he: `השאלה שחשפה את זה` },
        body: {
          en: `A student pushed back that \`SELECT ... FROM ... WHERE ...\` feels backwards — logically, you'd think first about the table (\`FROM\`), then the filter (\`WHERE\`), and only then which columns to keep (\`SELECT\`). Dr. Zuari's answer was direct: the written order is fixed syntax, and no, it cannot be rearranged to match how a person naturally thinks through the problem.`,
          he: `סטודנט דחף נגד שזה מרגיש הפוך — לוגית, היינו חושבים קודם על הטבלה (\`FROM\`), אחר כך על הפילטר (\`WHERE\`), ורק אז אילו עמודות לשמור (\`SELECT\`). התשובה של ד״ר זוארי הייתה ישירה: סדר הכתיבה הוא תחביר קבוע, ולא, אי אפשר לסדר אותו מחדש כדי להתאים לאיך שאדם חושב באופן טבעי דרך הבעיה.`,
        },
      },
      {
        heading: { en: `Written Order Is Not Evaluation Order`, he: `סדר הכתיבה הוא לא סדר ההערכה` },
        body: {
          en: `The resolution to the apparent contradiction: SQL's written syntax and SQL's actual logical processing order are two separate things. The engine conceptually works out the source table, then applies the filter, and only at the end decides which columns to display — which is exactly the intuitive order the student expected. The written clause order simply doesn't have to match the order in which the database engine reasons about the query.`,
          he: `הפתרון לסתירה לכאורה: התחביר הכתוב של SQL וסדר העיבוד הלוגי בפועל של SQL הם שני דברים נפרדים. המנוע מבחינה מושגית עובד תחילה על טבלת המקור, ואז מיישם את הפילטר, ורק בסוף מחליט אילו עמודות להציג — שזה בדיוק הסדר האינטואיטיבי שהסטודנט ציפה לו. סדר הסעיפים הכתוב פשוט לא חייב להתאים לסדר שבו מנוע בסיס הנתונים מנמק על השאילתה.`,
        },
      },
    ],
    principle: {
      en: `A fixed syntax and a fixed thought process are not required to agree — SQL's real lesson is learning to trust the syntax even when your intuition wants to write it differently.`,
      he: `תחביר קבוע ותהליך חשיבה קבוע לא חייבים להסכים — השיעור האמיתי של SQL הוא ללמוד לסמוך על התחביר גם כשהאינטואיציה רוצה לכתוב אותו אחרת.`,
    },
  },
  {
    number: '10',
    title: { en: `Check Yourself`, he: `בדקי את עצמך` },
    subtitle: {
      en: `Four questions this session's content earns — not generic SQL trivia`,
      he: `ארבע שאלות שהתוכן של המפגש הזה מזכה בהן — לא טריוויה כללית על SQL`,
    },
    sections: [
      {
        heading: { en: `On Foreign Key Tracing`, he: `על עקיבה אחרי מפתח זר` },
        body: {
          en: `A Users table has a row with \`address_id = 2\`. Does this mean the user lives in the city with ID 2? Answer: no — \`address_id = 2\` points to the address row whose own \`id\` is 2. Only that address row's \`city_id\` column reveals the actual city; collapsing the chain and matching the digit directly is exactly the mistake the whole class made live.`,
          he: `לטבלת Users יש שורה עם \`address_id = 2\`. האם זה אומר שהמשתמשת גרה בעיר עם ID מספר 2? תשובה: לא — \`address_id = 2\` מצביע על שורת הכתובת שה-\`id\` שלה עצמה הוא 2. רק עמודת \`city_id\` של שורת הכתובת הזו חושפת את העיר בפועל; לקפל את השרשרת ולהתאים את הספרה ישירות זו בדיוק הטעות שכל הכיתה עשתה בשידור חי.`,
        },
      },
      {
        heading: { en: `On Table Splitting`, he: `על פיצול טבלאות` },
        body: {
          en: `A city name is misspelled and repeated across 200 customer rows in one giant table. Why does moving that city into its own small table, referenced by a foreign key, matter more than it seems? Answer: in the giant table, fixing the typo requires editing all 200 rows individually; with the city in its own table, the same typo needs exactly one fix, regardless of how many customer rows reference it.`,
          he: `שם עיר שגוי בהקלדה וחוזר על עצמו ב-200 שורות לקוחות בטבלה ענקית אחת. למה להעביר את העיר הזו לטבלה קטנה משלה, מופנית אליה עם מפתח זר, משנה יותר משזה נראה? תשובה: בטבלה הענקית, תיקון הטעות דורש עריכת כל 200 השורות בנפרד; עם העיר בטבלה משלה, אותה טעות דורשת בדיוק תיקון אחד, לא משנה כמה שורות לקוחות מפנות אליה.`,
        },
      },
      {
        heading: { en: `On Duplicate Inserts`, he: `על הכנסות כפולות` },
        body: {
          en: `A notebook cell that inserts two rows is accidentally run four times, and no error appears — but the table now has eight rows instead of two. Why doesn't SQLite catch this automatically? Answer: SQLite has no memory of which cells "already ran" — every execution is treated as a brand-new, independent event, and the auto-incrementing primary key happily assigns a fresh ID to every duplicate without complaint.`,
          he: `תא במחברת שמכניס שתי שורות רץ בטעות ארבע פעמים, ושום שגיאה לא מופיעה — אבל לטבלה עכשיו יש שמונה שורות במקום שתיים. למה SQLite לא תופסת את זה אוטומטית? תשובה: ל-SQLite אין זיכרון של אילו תאים "כבר רצו" — כל הרצה מטופלת כאירוע חדש לגמרי ועצמאי, והמפתח הראשי שמעלה את עצמו אוטומטית מקצה בשמחה מזהה טרי לכל כפילות בלי תלונה.`,
        },
      },
      {
        heading: { en: `On Clause Order`, he: `על סדר הסעיפים` },
        body: {
          en: `A student argues \`SELECT ... FROM ... WHERE ...\` should be rewritten as \`FROM ... WHERE ... SELECT ...\` to match the logical order of thinking through a query. Why is this request refused, and is the student's logical order actually wrong? Answer: the student's logical order isn't wrong — that is roughly how the database engine actually evaluates the query internally. But SQL's written syntax is a fixed grammar, separate from its evaluation order, and cannot be rearranged to match either intuition or internal processing order.`,
          he: `סטודנטית טוענת ש-\`SELECT ... FROM ... WHERE ...\` צריך להיכתב מחדש כ-\`FROM ... WHERE ... SELECT ...\` כדי להתאים לסדר הלוגי של חשיבה דרך שאילתה. למה הבקשה הזו נדחית, והאם הסדר הלוגי של הסטודנטית באמת שגוי? תשובה: הסדר הלוגי של הסטודנטית לא שגוי — זה בערך איך מנוע בסיס הנתונים באמת מעריך את השאילתה מבפנים. אבל התחביר הכתוב של SQL הוא דקדוק קבוע, נפרד מסדר ההערכה שלו, ולא יכול להיות מסודר מחדש כדי להתאים לא לאינטואיציה ולא לסדר העיבוד הפנימי.`,
        },
      },
    ],
    principle: {
      en: `A memorized keyword order answers "what to type." These questions only answer to "what the database is actually doing with it."`,
      he: `סדר מילות מפתח שמושנן עונה על "מה להקליד". השאלות האלה עונות רק ל"מה בסיס הנתונים בעצם עושה עם זה".`,
    },
  },
];
